services:
  db:
    image: postgis/postgis:16-3.4
    container_name: roble_db
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      PGUSER: ${DATABASE_USER} # for Mac
      POSTGRES_USER: ${DATABASE_USER} # for Linux (not sure)
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: roble_web
    expose: 
      - 3000
    ports:
      - "3000:3000"
    
  backend: 
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: roble_backend
    command: sh -c "cd roble; python3 manage.py migrate --noinput && python3 manage.py createsuperuser --noinput ; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    expose :
      - 8000
    ports:  
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy