FROM node:18-alpine
 
# Set the working directory.
WORKDIR /app
 
# Copy the package.json file.
COPY ./frontend/package.json .
 
# Install application dependencies.
RUN npm install
 
# Copy the rest of the application files.
COPY ./frontend .
 
# Expose the port.
EXPOSE 3000
 
# Run the application.
CMD ["npm", "start"]