services:
  db:
    image: postgis/postgis:16-3.4
    container_name: roble_db
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      PGUSER: ${DATABASE_USER} # for Mac
      POSTGRES_USER: ${DATABASE_USER} # for Linux (not sure)
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    container_name: roble_web
    expose: 
      - 3000
    ports:
      - "3000:3000"
    
  geoserver: 
    image: docker.osgeo.org/geoserver:2.26.0
    container_name: roble_geoserver
    expose:
      - 8080
    ports:  
      - "8080:8080"
      
volumes:
  data: